services:
  plausible:
    image: ghcr.io/plausible/community-edition:v3.0.0
    labels:
      traefik.enable: "true"
      traefik.http.services.plausible.loadbalancer.server.port: 8000

      traefik.http.routers.plausible.entrypoints: "https"
      traefik.http.routers.plausible.rule: "Host(`statistics.filippo-orru.com`)"
      traefik.http.routers.plausible.service: plausible

      # Proxy traffic from /psb.js to "http://plausible:8000/js/plausible.js"
      traefik.http.routers.plausibleJs.entrypoints: "https"
      traefik.http.routers.plausibleJs.rule: "Host(`statistics.filippo-orru.com`) && Path(`/psb.js`)"
      traefik.http.routers.plausibleJs.service: plausible
      traefik.http.middlewares.plausibleJsReplacement.replacepath.path: "/js/plausible.js"
      traefik.http.routers.plausibleJs.middlewares: plausibleJsReplacement

    command: sh -c "sleep 2 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh run"
    expose:
      - 8000
    depends_on:
      - plausible_db
      - plausible_events_db
    env_file:
      - plausible-conf.env
  
  plausible_db:
    # supported versions are 12, 13, and 14
    image: postgres:14-alpine
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.12-alpine
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_SKIP_USER_SETUP=1
    tmpfs:
      - /var/log/clickhouse-server

volumes:
  db-data:
    driver: local
  event-data:
    driver: local
