include:
  - plausible/docker-compose.yaml

services:
  nginx:
    image: nginx:alpine
    volumes:
      - ./public:/usr/share/nginx/html
    labels:
      traefik.enable: "true"
      traefik.http.routers.filippo-orru.rule: "Host(`filippo-orru.com`, `www.filippo-orru.com`)"
      traefik.http.routers.filippo-orru.entrypoints: "https"
      traefik.http.routers.filippo-orru.tls: "true"
      traefik.http.services.filippo-orru.loadbalancer.server.port: "80"

  webhook-listener:
    build: 
      context: webhook-listener
      args:
        - PRE_BUILD_COMMAND=curl -L -o hugo.tar.gz https://github.com/gohugoio/hugo/releases/download/v0.133.0/hugo_extended_0.133.0_linux-arm64.tar.gz && tar -xvzf hugo.tar.gz && cp hugo /usr/bin/ && chmod +x /usr/bin/hugo
    expose:
      - 8080
    environment:
      - PORT=8080
      - COMMAND="cd /src && git config --global --add safe.directory /src && git pull && hugo --ignoreCache --minify -s /src -d /target"
    volumes:
      - ./:/src
      - ./public:/target
    secrets:
      - webhook_secret
    labels:
      traefik.enable: "true"
      traefik.http.routers.filippo-orru-webhook.rule: "Host(`filippo-orru.com`) && PathPrefix(`/webhook`)"
      traefik.http.routers.filippo-orru-webhook.entrypoints: "https"
      traefik.http.routers.filippo-orru-webhook.tls: "true"
      traefik.http.services.filippo-orru-webhook.loadbalancer.server.port: "8080"
  
  comments:
    image: ghcr.io/isso-comments/isso:release
    volumes:
      - type: bind
        source: ./services/isso-comments/isso.cfg
        target: /config/isso.cfg
      - './services/isso-comments/db:/db'
    expose:
      - 8080
    ports:
      - 8080:8080
    labels:
      traefik.enable: "true"
      traefik.http.routers.filippo-orru-comments.rule: "Host(`filippo-orru.com`, `www.filippo-orru.com`) && PathPrefix(`/isso`)"
      # traefik.http.routers.filippo-orru-comments.rule: "Host(`localhost`) && PathPrefix(`/isso`)"
      traefik.http.routers.filippo-orru-comments.middlewares: "filippo-orru-comments-stripprefix"
      traefik.http.middlewares.filippo-orru-comments-stripprefix.stripprefix.prefixes: "/isso"
      traefik.http.routers.filippo-orru-comments.entrypoints: "https"
      traefik.http.routers.filippo-orru-comments.tls: "true"
      traefik.http.services.filippo-orru-comments.loadbalancer.server.port: "8080"

secrets:
  webhook_secret:
    file: ./webhook.secret

networks:
  default:
    external: true
    name: traefik_proxy
